### ISSUE TITLE
jacred.service Active: failed

### ISSUE THREAD

**Issue by xam52** [immisterio/jacred-fdb#3]
Не стартует на debian 11.
Linux vpn2 5.10.0-27-amd64 #1 SMP Debian 5.10.205-2 (2023-12-31) x86_64 GNU/Linux.
На debian 12 и ubuntu 22.04 ok.

● jacred.service - jacred
     Loaded: loaded (/etc/systemd/system/jacred.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sun 2024-01-14 21:06:00 MSK; 39min ago
    Process: 491 ExecStart=/root/.dotnet/dotnet JacRed.dll (code=exited, status=203/EXEC)
   Main PID: 491 (code=exited, status=203/EXEC)
        CPU: 1ms

Jan 14 21:06:00 vpn2 systemd[1]: jacred.service: Scheduled restart job, restart counter is at 4.
Jan 14 21:06:00 vpn2 systemd[1]: Stopped jacred.
Jan 14 21:06:00 vpn2 systemd[1]: Started jacred.
Jan 14 21:06:00 vpn2 systemd[1]: jacred.service: Main process exited, code=exited, status=203/EXEC
Jan 14 21:06:00 vpn2 systemd[1]: jacred.service: Failed with result 'exit-code'.
Jan 14 21:06:00 vpn2 systemd[1]: jacred.service: Scheduled restart job, restart counter is at 5.
Jan 14 21:06:00 vpn2 systemd[1]: Stopped jacred.
Jan 14 21:06:00 vpn2 systemd[1]: jacred.service: Start request repeated too quickly.
Jan 14 21:06:00 vpn2 systemd[1]: jacred.service: Failed with result 'exit-code'.
Jan 14 21:06:00 vpn2 systemd[1]: Failed to start jacred.

**Comment by thevitas** [comment]
Версия от 26.01.2024 не работает, запускается, начинает парсить торренты и создавать базу, падает через какое то время. Ubuntu 22.04 - 5.15.0-86-generic x86_64

systemctl status jacred
× jacred.service - jacred
     Loaded: loaded (/etc/systemd/system/jacred.service; enabled; vendor preset: enabled)
     Active: failed (Result: core-dump) since Wed 2024-02-07 11:20:24 MSK; 6s ago
    Process: 1729159 ExecStart=/root/.dotnet/dotnet JacRed.dll (code=dumped, signal=ABRT)
   Main PID: 1729159 (code=dumped, signal=ABRT)
        CPU: 1.020s

фев 07 11:20:24 vpn-ams.beta-net.ru systemd[1]: jacred.service: Main process exited, code=dumped, status=6/ABRT
фев 07 11:20:24 vpn-ams.beta-net.ru systemd[1]: jacred.service: Failed with result 'core-dump'.
фев 07 11:20:24 vpn-ams.beta-net.ru systemd[1]: jacred.service: Consumed 1.020s CPU time.
фев 07 11:20:24 vpn-ams.beta-net.ru systemd[1]: jacred.service: Scheduled restart job, restart counter is at 5.
фев 07 11:20:24 vpn-ams.beta-net.ru systemd[1]: Stopped jacred.
фев 07 11:20:24 vpn-ams.beta-net.ru systemd[1]: jacred.service: Consumed 1.020s CPU time.
фев 07 11:20:24 vpn-ams.beta-net.ru systemd[1]: jacred.service: Start request repeated too quickly.
фев 07 11:20:24 vpn-ams.beta-net.ru systemd[1]: jacred.service: Failed with result 'core-dump'.
фев 07 11:20:24 vpn-ams.beta-net.ru systemd[1]: Failed to start jacred.

**Comment by thevitas** [comment]
Удалил свой init.conf от прошлых версий, залил из архива и добавил только строку с apikey. Все заработало.

**Comment by xam52** [comment]
Удалил:
/home/jacred/
/root/.dotnet
/root/dotnet-install.sh
/etc/systemd/system/jacred.service
переустановил и всё заработало
