### ISSUE TITLE
Статичные ресурсы не загружаются с API ключом

### ISSUE THREAD

**Issue by gentslava** [immisterio/jacred-fdb#7]
### Проблема:
После установки параметра **apikey** в _init.conf_ статичные ресурсы (стили, скрипты, иконки) из wwwroot перестают загружаться.
![image](https://github.com/immisterio/jacred-fdb/assets/14369958/857a8e1e-91b7-4d75-9b6b-da1568a142ba)
![image](https://github.com/immisterio/jacred-fdb/assets/14369958/9180f9d7-108c-46a3-b9de-6116bcdc9fea)

Waterfall из вкладки Network Devtools,
`apikey: ""`
![image](https://github.com/immisterio/jacred-fdb/assets/14369958/63057949-a9c5-4c08-8b5a-b2fdd4c827b0)

`apikey: "rus"`
![image](https://github.com/immisterio/jacred-fdb/assets/14369958/a5952e6e-2531-4aa1-b804-f99d6c22ef0f)

Кроме того, если открыть ссылку на ресурс без get параметра apikey, будет пустой экран (пустой документ)
![image](https://github.com/immisterio/jacred-fdb/assets/14369958/8919eacc-7539-4a5d-b5aa-87ff0b781647)
Добавим apikey, документ загрузится
![image](https://github.com/immisterio/jacred-fdb/assets/14369958/c8555d79-fefe-4b20-bc28-c0fc4c34a82b)

### Решение:
Статичные файлы должны загружаться независимо от наличия apikey в _init.conf_.

**Comment by thevitas** [comment]
Аналогично. Думал у меня что сломалось, а оно вот в чем дело. А разработчик похоже бросил проектом заниматься.

**Comment by immisterio** [comment]
Исправил
