### ISSUE TITLE
Обновления

### ISSUE THREAD

**Issue by thevitas** [immisterio/jacred-fdb#8]
Подскажите, проект обновляться будет?
И что надо настроить чтоб в выдаче лампы были красивые прямоугольники с данными фильма (разрешение, перевод, субтитры)?

**Comment by emergy** [comment]
Дааа. Тоже хотел что-то красивое, как <projectname>.xyz, но в результате какой-то не работоспособный поиск, неполноценная документация, жор CPU и RAM. В общем-то остался на jackett

**Comment by thevitas** [comment]
> Дааа. Тоже хотел что-то красивое, как .xyz, но в результате какой-то не работоспособный поиск, неполноценная документация, жор CPU и RAM. В общем-то остался на jackett

У меня ничего не жрет, поиск норм ищет. Единственное обновлений давно нет никаких.

**Comment by immisterio** [comment]
Обновляется если есть ошибки в работе

**Comment by thevitas** [comment]
> Обновляется если есть ошибки в работе

Вам уже написали про ошибку работы WEBа, а Вы все никак не исправите.
